#!/bin/bash
# Author: Luis R. Rodriguez <mcgrof@gmail.com>
# This cronjob archives the compat-wireless-2.6 tarballs

# Exit immediately if an error is encountered
set -e

source "`dirname $0`/config.sh"

DEST_DIR="${COMPAT_ARCHIVE}/${YEAR}/${MONTH}"
mkdir -p $DEST_DIR

for i in noflags p c; do
        if [[ $i != "noflags" ]]; then
                # this will just be "pc" when using both
                # pending patches and crap patches
                FILE_POSTFIX="${FILE_POSTFIX}$i"
		COMPAT_TAR="${ORIG_COMPAT_TAR}-${FILE_POSTFIX}.tar.bz2"
	else
		COMPAT_TAR="${ORIG_COMPAT_TAR}.tar.bz2"
        fi
	if [ -f $COMPAT_ARCHIVE/$COMPAT_TAR ]; then
		cp -f $COMPAT_ARCHIVE/$COMPAT_TAR $DEST_DIR
	fi
done

cd $DEST_DIR
/usr/bin/sha1sum *.tar.bz2 > $COMPAT_SHA1

chmod 755 *
